
services:

  valkey:
    container_name: valkey
    hostname: valkey
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    #pull_policy: always
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  augmentoolkit:
    container_name: augmentoolkit
    hostname: augmentoolkit
    user: root
    depends_on:
      - valkey
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/dockerfile
    volumes:
    - ./data/output:/app/outputs
    - ./data/inputs:/app/inputs/mydata
    - ./data/configs:/app/external_configs/myconfigs
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=3
    ports:
    - "127.0.0.1:8000:8000" # api
    - "127.0.0.1:5173:5173" # ui
    - "127.0.0.1:8083:8082" # vllm
    # devices:
    #   - nvidia.com/gpu=all
    #   - /dev/video0
